### PR TITLE
Clean-up: removing/obsoletizing deferred proposals

### PR DESCRIPTION
**Pull request by blimpa**
Removed MIP102c3-SP1 from repo since 1) it's empty and 2) there are no posterior MIP102c3 subproposals.

Since you can't have empty folders in GitHub, added placeholder

@Le-Bateleur-2023 , @VoteWizard

### CODE REVIEW

**Comment by 0xldr** [comment]
We are curious why MIP102c3-SP1 is being deleted rather than being marked as Obsolete?

**Comment by VoteWizard** [comment]
I'd also like to know why MIP102c3-SP1 is being deleted rather than being marked as Obsolete. You can merge the PR if there is a good reason

**Comment by 0xldr** [comment]
@blimpa what is the status of this PR?

**Comment by 0xldr** [comment]
Made obsolete by https://github.com/makerdao/mips/pull/1117

**Pull request closed without merging**
