### PR TITLE
Updating MIP38c2: Core Unit State

### PR DESCRIPTION
**Pull request by blimpa**
@Davidutro, @CPSTL, please review and merge

### CODE REVIEW

**Comment by Davidutro** [comment]
The format seems very piled on top of itself
image

Any way we can change it to be more of a list view? Or a table?

Example:
image

**Comment by blimpa** [comment]
Yeah, you're right. I feel the same way. Those lists look good!

Gimme two minutes

**Review by CPSTL — COMMENTED** [review]
@blimpa The template section (NAME-XXX) formatting is a little off but other than that, it looks great 👍

**Comment by Davidutro** [comment]
As a general format rule, add a space after headers in markdown @blimpa 
otherwise, that last commit looks great

**Comment by blimpa** [comment]
> As a general format rule, add a space after headers in markdown @blimpa
> otherwise, that last commit looks great

I don't see where I contravened that rule :0

**Comment by Davidutro** [comment]
The headers for the CU names and the lists underneath are missing spaces.

image
image

**Comment by blimpa** [comment]
@Davidutro , I totally misread what you wrote. Hah. Sorry

**Comment by Davidutro** [comment]
Heh no worries, always happy to explain 😃

**Pull request merged**
