### PR TITLE
[AMENDMENTS] MIP0, MIP16  - Core Unit Operating Model

### PR DESCRIPTION
**Pull request by LongForWisdom**
Courtesy @juan-fintech. Please double check everything is present when convenient.

### CODE REVIEW

**Comment by Davidutro** [comment]
DO NOT MERGE until accepted

**Review by juan-fintech — APPROVED** [review]
Thanks for the upload, @LongForWisdom .

**Comment by Davidutro** [comment]
Just a reminder that all but MIP24 amendments were formally submitted with the rest of the Core Unit stuff.

I would remove those amendments from this PR and submit those separately

**Comment by Davidutro** [comment]
@juan-fintech @LongForWisdom 

Can one of you please remove the MIP 24 amendments from this PR so I can merge it into master :)

MIP0 and MIP 16 amendments passed with the March MIPs bundle.

**Comment by LongForWisdom** [comment]
Done.

**Comment by Davidutro** [comment]
MIP 0 and 16 amendments were passed in the March MIPs bundle and so I am merging these changes.

**Pull request merged**
