### PR TITLE
Marking inactive/superseded CU SPs as obsolete

### PR DESCRIPTION
**Pull request by blimpa**
Plus some minor fixes

### CODE REVIEW

**Comment by ghost** [comment]
Why haven't you marked MDS-001, MKT-001, or EVENTS-001 as Obsolete under their respective MIP39c2 proposals?

**Review by ghost — CHANGES_REQUESTED** [review]
One thing to double check is that we haven't marked a DAI budget as obsolete that contains active MKR vesting proposals

**Comment by blimpa** [comment]
> Why haven't you marked MDS-001, MKT-001, or EVENTS-001 as Obsolete under their respective MIP39c2

Not sure why I missed that/didn't commit that. I'll get to it now

**Comment by blimpa** [comment]
> One thing to double check is that we haven't marked a DAI budget as obsolete that contains active MKR vesting proposals

I tried to be mindful of that, but maybe some slipped through. I'll recheck

**Review by Gala-G — COMMENTED** [review]
I believe we forgot to include:
MIP40c3-SP52 (superseded by MIP40c3-SP82)
MIP40c3-SP55 (superseded by MIP40c3-SP87)

Apart from that, LGTM

**Review by Gala-G — COMMENTED** [review]
I believe we have to mark these as obsolete...
MIP39c2-SP2 (RISK-001) - superseded by MIP39c2-SP35
MIP39c2-SP5 (MKT-001)
MIP39c2-SP6 (MDS-001)
MIP39c2-SP8 (COM-001) - superseded by MIP39c2-SP30
MIP39c2-SP12 (CES-001) - superseded by MIP39c2-SP37
MIP39c2-SP22 (DIN-001) - superseded by MIP39c2-SP31 
MIP39c2-SP27 (SF-001) - superseded by MIP39c2-SP36
MIP39c2-SP32 (EVENTS-001)

**Review by Gala-G — COMMENTED** [review]
And here we missed these ones
MIP41c4-SP6
MIP41c4-SP9
MIP41c4-SP23
MIP41c4-SP33

**Comment by Gala-G** [comment]
> 

I just double checked that all budgets being marked as obsolete do not have an active MKR budget on them.

**Comment by ghost** [comment]
@Gala-G @blimpa please resolve conflicts.

Also, can we please remove the "active" tags from proposals we are marking as obsolete since they are no longer active by definition?

**Comment by blimpa** [comment]
> @Gala-G @blimpa please resolve conflicts.
> 
> Also, can we please remove the "active" tags from proposals we are marking as obsolete since they are no longer active by definition?

Done. Thank you both

**Pull request merged**
