### PR TITLE
Create MIP55c3-SP9.md

### PR DESCRIPTION
**Pull request by Gala-G**

### CODE REVIEW

**Review by flexgod76 — APPROVED** [review]
@Gala-G is this a project for anyone or for me

**Comment by Gala-G** [comment]
@flexgod76 This is the official repo for MakerDAO’s Maker Improvement Proposals. Are you looking to contribute to MakerDAO?

**Comment by flexgod76** [comment]
Yes

**Comment by flexgod76** [comment]
> @flexgod76 This is the official repo for MakerDAO’s Maker Improvement Proposals. Are you looking to contribute to MakerDAO?

Yes

**Comment by Gala-G** [comment]
Please reach out to @prose11 - one of our Governance Facilitators - on forum.makerdao.com

Thank you.

**Pull request merged**
