### PR TITLE
Core Unit MIP Set (38, 39, 40, 41)

### PR DESCRIPTION
**Pull request by juan-fintech**
Corrected MIP Set + Proposals

### CODE REVIEW

**Comment by juan-fintech** [comment]
@CPSTL , @LongForWisdom 

MIP Set (38, 39, 40, 41) + Subproposals.

I'll update it them in the forum as well.

Thanks,

Juan

**Comment by CPSTL** [comment]
@juan-fintech Thanks, Juan! Would you be able to make this PR to the RFC branch instead?

**Comment by juan-fintech** [comment]
Sure.

I thought we were not using RFCs anymore...

**Comment by CPSTL** [comment]
@juan-fintech Thanks! We are working on the branch management updates/plans but have not started the deprecation process yet. So, for now, the process is still the same.

**Pull request closed without merging**
