### PR TITLE
MIP4c2-SP27 PR

### PR DESCRIPTION
**Pull request by Gala-G**
To be merged in upon ratification.

### CODE REVIEW

**Comment by flexgod76** [comment]
> To be merged in upon ratification.

Ready

**Review by flexgod76 — COMMENTED** [review]
Im not fully understanding the proposal regarding merge ratification but I'm guessing merge means to come together and I guess the ratification part of it is the voting of it it's changing or making something better  if that's my interpretation of it again like I said I'm not a large firm or some mobile major company that has major resources that's not me but I'm new to all this and I'm willing to learn I'm an open book if it's positive and it's in good standards not hurting anybody or putting anybody in harm in anyway shape form or fashion   then I will make my decision based on that.

**Review by flexgod76 — APPROVED** [review]
Merge

**Comment by flexgod76** [comment]
So what's goin help me understand

**Review by flexgod76 — APPROVED** [review]

**Review by Flexgod69iner — COMMENTED** [review]
Please good or bad

**Pull request merged**
